algoritmo "Calcular o quadrado de determinado número. "
// Função :  Calcular notação.
// Autor :  Matheus Alves
// Data : 03/04/2022
// Seção de Declarações 
var
numero: inteiro
numeroaoquadrado: inteiro
inicio
// Seção de Comandos 
escreval("Defina o valor do número.")
leia(numero)

numeroaoquadrado <- quad (numero)

escreval("O resultado do número ",numero," elevado ao quadrado é ",numeroaoquadrado,".")

fimalgoritmo
