algoritmo "Nome e saudação."
// Função : Nome e saudação.
// Autor : Matheus Alves
// Data : 04/04/2022
// Seção de Declarações 
var
nome: caractere
sexo: caractere
inicio
// Seção de Comandos
escreval("Informe o nome da pessoa.")
leia(nome)

escreval("Informe o sexo da pessoa.")
leia(sexo)

se sexo= "masculino" entao
escreval("Ilmo. Sr")
senao
     se sexo = "feminino" entao
     escreval("Ilma. Sra.")
     senao
fimse
fimse
fimalgoritmo
