algoritmo "Valor na faixa de 1 até 9."
// Função : Calcular valores numa determinada faixa.
// Autor :  Matheus Alves
// Data : 04/04/2022
// Seção de Declarações 
var
valor: inteiro
inicio
// Seção de Comandos 
escreval("Defina um valor.")
leia(valor)

se (valor >=1) e (valor <=9) entao
escreval("O valor está na faixa permitida.")
senao
escreval("O valor não está na faixa permitida.")
fimse
fimalgoritmo
